### ISSUE TITLE
Scraping is unintuitive

### ISSUE THREAD

**Issue by yogwoggf** [luttje/glua-api-snippets#2]
Is there a reason for scraping the HTML and "traversing" links? You can scrape markup and get pages using their specific endpoints and formats.

- Page list in JSON: https://wiki.facepunch.com/gmod/~pagelist?format=json
- Page in markup: https://wiki.facepunch.com/gmod/GM:DoPlayerDeath?format=text

I think the code would be clearer if you were to scrape using the markup instead of the HTML, but it's just a suggestion.

**Comment by luttje** [comment]
Hey thanks for your interest.

You're exactly right. To be honest I haven't played Gmod in a while, nor have I looked seriously at the Gmod Wiki. This project was more an excuse to code something and I hadn't even found the JSON endpoints 😅

Thanks for your suggestion though, it would make the scraping more intuitive.

I'll mark this as a future improvement. Though I probably won't work on it anytime soon, since everything works fine atm.

**Comment by luttje** [comment]
@all-contributors please add @yogwoggf for ideas
