### ISSUE TITLE
`Panel` tooltips are not only `string`

### ISSUE THREAD

**Issue by b0mbie** [luttje/glua-api-snippets#58]
[The page for `Panel:SetTooltip`](https://wiki.facepunch.com/gmod/Panel:SetTooltip) says that `str` can actually be either a `string` _or_ `false` for no tooltip:
> # Arguments
> 1. `string` str
> The text to be displayed in the tooltip. Set false to disable it.

Then, [the page for `Panel:GetTooltip`](https://wiki.facepunch.com/gmod/Panel:GetTooltip) also says that the return value is the tooltip text, _if it was set_:
> # Returns
> 1. `string` tooltip
> The tooltip text, if it was set.

The tooltip type can possibly defined to be `string|false` for the `Panel:SetTooltip` parameter type, though I'm not sure about the return type for `Panel:GetTooltip`.

This change would fix the diagnostics for the example presented on the page for `Panel:SetTooltip`:
![image](https://github.com/user-attachments/assets/f27f38fb-6d90-4c60-9762-589475c5d2ca)

**Comment by luttje** [comment]
Heya, thanks for reporting.

If I understand you correctly, then this can be fixed by editting the wiki.

I looked up an example that also allows multiple types for a parameter and found [concommand.Add](https://wiki.facepunch.com/gmod/concommand.Add) which is typed correctly for its `flags` parameter: https://github.com/luttje/glua-api-snippets/blob/d4940ffbc406630b84588608f218c8aa27db5266/library/concommand.lua#L35

You can [see on the wiki edit page](https://wiki.facepunch.com/gmod/concommand.Add~edit) that this is achieved with an argument documented like this:
```xml
<arg name="flags" type="number" alttype="table" default="0">Console command modifier flags. Either a bitflag, or a table of enums. See <page>Enums/FCVAR</page>.</arg>
```

If this answers your question, then it'd be great if you could edit the wiki to document this `alttype`. Let me know if this is the case and I'll close this issue.

Next month when the scraper updates I'll update the extension in LLS-Addons

**Comment by robotboy655** [comment]
I think the wiki has it misdocumented, its not `false` to disable it (it works, but as a coincidence), it's omitting the argument that is intended, or `nil`. I have updated the wiki page.

**Comment by b0mbie** [comment]
Oh! That certainly makes more sense. I think it'll be ok to close this now, then.
