### ISSUE TITLE
Functions and variables that need to be hardcoded

### ISSUE THREAD

**Issue by Vurv78** [luttje/glua-api-snippets#9]
* `SERVER`, `CLIENT`, `MENU_DLL` as `boolean?`
* `Color()` should return a `Color`

Also, `vgui.Create` could return the proper subtype based on the first parameter using [generic captures](https://github.com/LuaLS/lua-language-server/wiki/Annotations#generic), although this is likely LuaLS specific, so unsure of what you want to do with this:

```lua
---@generic T: Panel
---@param classname `T`
---@param parent Panel?
---@param name string?
---@return T
local function vgui_Create(classname, parent, name)
	return vgui.Create(classname, parent, name)
end
```

So calling `vgui_Create("DLabel")` would assign it the type `DLabel` which extends `Panel`.

**Comment by luttje** [comment]
Thanks so much for the detailed report, this will save me a ton of time.

Seeing how LuaLS seems the most maintained and extensive, I'll likely drop support for EmmyLua and use that Generic Capture annotation.

For this issue, along with #7 I will likely implement a file in root (e.g: _overloads.lua) that gets copied after scraping the wiki. It can contain all these fixes.

For the Color() function to return a Color instead of a table, I would prefer the wiki to be corrected (if that is correct). But until that time we could keep our fixes in that proposed _overloads.lua.
